// Generated by CoffeeScript 1.3.3
var ass;

ass = {};

ass.init = function() {
  var angle, angleStr, canvas, center, context, l, radius;
  canvas = $("#shakecanvas")[0];
  context = canvas.getContext('2d');
  angle = Math.floor(Math.random() * 360) * 1.0;
  center = 32.0;
  radius = 30.0;
  l = ass.getCircleCoordinates(center, center, radius, angle);
  context.beginPath();
  context.moveTo(center, center);
  context.lineTo(l.x, l.y);
  context.strokeStyle = '#ff0000';
  context.stroke();
  context.beginPath();
  context.arc(center, center, radius, 0, 2 * Math.PI, false);
  context.stroke();
  angleStr = 'rotate(' + angle + 'deg)';
  $('.item').css({
    '-transform': angleStr,
    '-ms-transform': angleStr,
    '-moz-transform': angleStr,
    '-webkit-transform': angleStr,
    '-o-transform': angleStr
  }).html(angle);
  return ass.counter = 0;
};

ass.getCircleCoordinates = function(x, y, radius, angle) {
  var result;
  result = {};
  result.x = x + radius * Math.cos(angle * Math.PI / 180.0);
  result.y = y - radius * Math.sin(angle * Math.PI / 180.0);
  return result;
};

ass.animate = function() {
  $('#header').append(ass.counter);
  console.log('counter = ' + ass.counter);
  ass.counter++;
  return window.setInterval(ass.animate, 10);
};

$(document).ready(function() {
  console.log('ready!');
  ass.init();
  return ass.animate();
});
